services:
  db:
    image: postgres:14
    container_name: autoparts_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: autoparts_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # внешний порт 5433, внутри контейнера остаётся 5432

  bot:
    image: evgen1771/autoparts-bot:latest
    container_name: autoparts_bot
    env_file: .env
    restart: always
    depends_on:
      - db


volumes:
  db_data:
