version: '3.8'

services:
  bot:
    image: evgen1771/autoparts-bot:latest
    container_name: autoparts_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - autoparts_network

  db:
    image: postgres:13
    container_name: autoparts_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - autoparts_network

volumes:
  postgres_data:

networks:
  autoparts_network:
    driver: bridge
